import OpenAI from 'openai';

const DEFAULT_TEXT_MODEL = 'openai/gpt-oss-20b';
const DEFAULT_VISION_MODEL = 'meta-llama/llama-4-scout-17b-16e-instruct';

export class AICommentGenerator {
    private readonly client: OpenAI;
    private readonly textModel: string;
    private readonly visionModel: string;
    private readonly temperature: number = 0.9;
    private readonly maxOutputTokens: number = 120;

    constructor(apiKey: string, options?: { textModel?: string; visionModel?: string }) {
        if (!apiKey) {
            throw new Error('Groq API key is not provided in config.ts.');
        }

        this.client = new OpenAI({
            apiKey,
            baseURL: 'https://api.groq.com/openai/v1',
        });

        this.textModel = options?.textModel || DEFAULT_TEXT_MODEL;
        this.visionModel = options?.visionModel || DEFAULT_VISION_MODEL;
    }

    private buildPrompt(postText: string, targetUsername: string, promptHint?: string): string {
        let prompt = `You are an expert at writing engaging, human-like Instagram comments.
Your goal is to write a comment for a post by @${targetUsername}.

Post content: "${postText || 'The post has no text caption, so comment on the photo/video itself.'}"

`;

        if (promptHint) {
            prompt += `Important context to guide your comment: ${promptHint}\n\n`;
        }

        prompt += `Your Instructions:
1.  Write a super short and relevant comment.
2.  The comment MUST sound authentic and not like it was generated by a bot.
3.  Refer to something specific from the post content if possible.
4.  If there's an image provided, comment on what you see in the image.
5.  Keep it concise (1 sentence is ideal).
6.  ABSOLUTELY NO emojis.
7.  ABSOLUTELY NO hashtags.
8.  Vary your tone and phrasing. Avoid generic compliments like "Great post!".
9.  Don't ask questions or try to start a conversation.
10.  If the post is a video, comment on the video content.
11.  Don't share personal opinions or experiences or relate to anything.
12. Dont write super generic comments like "This is so inspiring!" or "Love this!".
13. Don't use exclamation marks or any punctuation that implies excitement.
14. Do not use first person pronouns like "I" or "me".


Write only the final comment text below. Do not add quotation marks around your response.`;

        return prompt;
    }

    private buildReplyPrompt(
        postText: string,
        postOwnerUsername: string,
        commenterUsername?: string,
        commenterText?: string,
        promptHint?: string
    ): string {
        let prompt = `You are an expert at writing short, natural Instagram replies.
You are replying to a comment that mentioned our account on a post by @${postOwnerUsername}.

Post content: "${postText || 'The post has no text caption, so reply based on the photo/video itself.'}"
`;

        if (commenterUsername) {
            prompt += `Commenter username: @${commenterUsername}\n`;
        }
        if (commenterText) {
            prompt += `Comment text: "${commenterText}"\n`;
        }

        if (promptHint) {
            prompt += `\nImportant context to guide your reply: ${promptHint}\n`;
        }

        prompt += `
Your Instructions:
1. Write a short, relevant reply that acknowledges the mention.
2. The reply MUST sound authentic and not like it was generated by a bot.
3. Refer to something specific from the post content if possible.
4. If there's an image provided, comment on what you see in the image.
5. Keep it concise (1 sentence is ideal).
6. ABSOLUTELY NO emojis.
7. ABSOLUTELY NO hashtags.
8. Avoid generic compliments like "Great post!" or "Love this!".
9. Don't ask questions or try to start a conversation.
10. If the post is a video, comment on the video content.
11. Don't share personal opinions or experiences.
12. Don't use exclamation marks or overly excited punctuation.
13. Do not use first person pronouns like "I" or "me".

Write only the final reply text below. Do not add quotation marks around your response.`;

        return prompt;
    }

    private async generateWithPrompt(
        promptText: string,
        imageUrl?: string,
        videoUrl?: string
    ): Promise<string> {
        try {
            const finalPrompt = videoUrl ? `${promptText}\n\nMedia type: video.` : promptText;
            const modelToUse = imageUrl ? this.visionModel : this.textModel;

            const content = imageUrl
                ? [
                      { type: 'text', text: finalPrompt },
                      { type: 'image_url', image_url: { url: imageUrl } },
                  ]
                : finalPrompt;

            if (videoUrl && !imageUrl) {
                console.log(`[AI_INFO] Video URL detected but no image available: ${videoUrl.substring(0, 80)}...`);
            }

            const response = await this.client.chat.completions.create({
                model: modelToUse,
                messages: [
                    {
                        role: 'user',
                        content,
                    },
                ],
                temperature: this.temperature,
                max_tokens: this.maxOutputTokens,
            });

            const text = response.choices?.[0]?.message?.content?.trim() ?? '';
            if (!text) {
                throw new Error('AI returned an empty comment.');
            }
            return text.replace(/"/g, '');
        } catch (error) {
            console.error(`[AI_ERROR] Groq request failed. Error:`, error);
            throw new Error(`Failed to generate comment using the provided API key.`);
        }
    }

    public async generateInstagramComment(
        postText: string,
        targetUsername: string,
        promptHint?: string,
        imageUrl?: string,
        videoUrl?: string
    ): Promise<string> {
        const promptText = this.buildPrompt(postText, targetUsername, promptHint);
        return this.generateWithPrompt(promptText, imageUrl, videoUrl);
    }

    public async generateInstagramReply(
        postText: string,
        postOwnerUsername: string,
        commenterText?: string,
        commenterUsername?: string,
        promptHint?: string,
        imageUrl?: string,
        videoUrl?: string
    ): Promise<string> {
        const promptText = this.buildReplyPrompt(
            postText,
            postOwnerUsername,
            commenterUsername,
            commenterText,
            promptHint
        );
        return this.generateWithPrompt(promptText, imageUrl, videoUrl);
    }
}
